/**
 * Config Generator
 * 
 * Generates platform-specific configuration files based on user selections.
 */

export type Platform = 'railway' | 'render' | 'flyio' | 'local';
export type PostgresOption = 'managed' | 'neon' | 'supabase' | 'external';

export interface DeploymentConfig {
  platform: Platform;
  postgres: PostgresOption;
  appName?: string;
  todoistApiKey?: string;
  claudeApiKey?: string;
  databaseUrl?: string;
}

export function generateRailwayConfig(config: DeploymentConfig): string {
  const railwayConfig = {
    $schema: 'https://railway.app/railway.schema.json',
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: 'api/Dockerfile',
    },
    deploy: {
      startCommand: 'node dist/main',
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 10,
    },
  };

  return JSON.stringify(railwayConfig, null, 2);
}

export function generateRenderConfig(config: DeploymentConfig): string {
  const services: any[] = [
    {
      type: 'web',
      name: 'danny-api',
      env: 'docker',
      dockerfilePath: './api/Dockerfile',
      dockerContext: './api',
      envVars: [
        { key: 'NODE_ENV', value: 'production' },
        { key: 'RUN_MODE', value: 'http' },
        { key: 'PORT', value: '8080' },
      ],
    },
  ];

  if (config.postgres === 'managed') {
    services.push({
      type: 'pg',
      name: 'danny-db',
      plan: 'free',
    });
  }

  const renderConfig = {
    services,
  };

  return `# Render Blueprint Configuration
# Generated by Danny Tasks Deployment Wizard

${JSON.stringify(renderConfig, null, 2)}`;
}

export function generateFlyToml(config: DeploymentConfig): string {
  const appName = config.appName || 'danny-tasks-api';

  return `# fly.toml - Danny Tasks API
# App name: ${appName}
# See https://fly.io/docs/reference/configuration/

app = "${appName}"
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  RUN_MODE = 'http'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
`;
}

export function generateEnvExample(config: DeploymentConfig): string {
  const envVars: string[] = [
    '# Danny Tasks Environment Variables',
    '# Copy this to .env and fill in your values',
    '',
    '# Required',
    `TODOIST_API_KEY=${config.todoistApiKey || 'your_todoist_api_key_here'}`,
    `CLAUDE_API_KEY=${config.claudeApiKey || 'your_claude_api_key_here'}`,
    '',
    '# Database',
  ];

  if (config.postgres === 'managed') {
    envVars.push('# DATABASE_URL will be automatically set by the platform');
  } else if (config.databaseUrl) {
    envVars.push(`DATABASE_URL=${config.databaseUrl}`);
  } else {
    envVars.push(`DATABASE_URL=postgresql://user:password@host:5432/dbname`);
  }

  envVars.push('');
  envVars.push('# Optional');
  envVars.push('DATABASE_TYPE=postgres');
  envVars.push('NODE_ENV=production');
  envVars.push('RUN_MODE=http');
  envVars.push('PORT=8080');

  return envVars.join('\n');
}

export function generateDockerCompose(config: DeploymentConfig): string {
  return `version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: danny-api
    environment:
      - NODE_ENV=production
      - RUN_MODE=http
      - DATABASE_URL=\${DATABASE_URL}
      - TODOIST_API_KEY=\${TODOIST_API_KEY}
      - CLAUDE_API_KEY=\${CLAUDE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - danny-network

  postgres:
    image: postgres:15-alpine
    container_name: danny-postgres
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - danny-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: danny-web
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - danny-network

volumes:
  postgres-data:

networks:
  danny-network:
    driver: bridge
`;
}

export function downloadFile(filename: string, content: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
