/**
 * Fly.io Deployment Guide
 * 
 * Detailed step-by-step guide for deploying to Fly.io.
 */

import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';

export default function FlyioGuide(): JSX.Element {
  return (
    <Layout title="Fly.io Deployment Guide" description="Deploy Danny Tasks to Fly.io">
      <div style={{ padding: '2rem 1rem', maxWidth: '900px', margin: '0 auto' }}>
        <div style={{ marginBottom: '2rem' }}>
          <Link to="/deployment">← Back to Deployment Wizard</Link>
        </div>

        <h1>Fly.io Deployment Guide</h1>
        <p className="text--secondary">
          Fly.io offers container-based deployment with Fly Postgres. Great for production workloads.
        </p>

        <h2>Prerequisites</h2>
        <ul>
          <li>GitHub account with your repository</li>
          <li>Fly.io account (<a href="https://fly.io" target="_blank" rel="noopener noreferrer">Sign up</a>)</li>
          <li>Fly CLI installed (<code>curl -L https://fly.io/install.sh | sh</code>)</li>
          <li>Todoist API key</li>
          <li>Claude API key</li>
        </ul>

        <h2>Step 1: Install Fly CLI</h2>
        <p>Install the Fly CLI on your local machine:</p>
        <pre><code>curl -L https://fly.io/install.sh | sh</code></pre>
        <p>Or use your package manager:</p>
        <ul>
          <li>macOS: <code>brew install flyctl</code></li>
          <li>Windows: <code>scoop install flyctl</code></li>
          <li>Linux: Use the install script above</li>
        </ul>

        <h2>Step 2: Authenticate</h2>
        <p>Sign up or log in to Fly.io:</p>
        <pre><code>fly auth signup</code></pre>
        <p>Or if you already have an account:</p>
        <pre><code>fly auth login</code></pre>

        <h2>Step 3: Prepare Configuration</h2>
        <ol>
          <li>Copy the <code>fly.toml</code> file (generated by the wizard) to the <code>api/</code> directory</li>
          <li>Update the <code>app</code> field with your desired app name (or leave it to be set during launch)</li>
        </ol>

        <h2>Step 4: Launch Your App</h2>
        <ol>
          <li>Navigate to the <code>api/</code> directory:</li>
          <pre><code>cd api</code></pre>
          <li>Run the launch command:</li>
          <pre><code>fly launch</code></pre>
          <li>Follow the prompts:
            <ul>
              <li>Choose an app name (or use the one from fly.toml)</li>
              <li>Select a region (e.g., <code>iad</code> for US East)</li>
              <li>When asked about Postgres, choose based on your preference:
                <ul>
                  <li><strong>Yes</strong> - Create a new Postgres database (managed)</li>
                  <li><strong>No</strong> - Use external database (set DATABASE_URL manually)</li>
                </ul>
              </li>
            </ul>
          </li>
        </ol>

        <h2>Step 5: Create Postgres Database (If Not Done During Launch)</h2>
        <p>If you didn't create Postgres during launch, create it now:</p>
        <pre><code>fly postgres create --name danny-tasks-db</code></pre>
        <p>Attach it to your app:</p>
        <pre><code>fly postgres attach danny-tasks-db --app your-app-name</code></pre>
        <p>This automatically sets <code>DATABASE_URL</code> as a secret.</p>

        <h2>Step 6: Set Secrets</h2>
        <p>Set your environment variables as Fly secrets:</p>
        <pre><code>fly secrets set TODOIST_API_KEY="your_todoist_key"
fly secrets set CLAUDE_API_KEY="your_claude_key"</code></pre>
        <p>If using an external database:</p>
        <pre><code>fly secrets set DATABASE_URL="postgresql://user:pass@host:5432/dbname"</code></pre>
        <p>View all secrets:</p>
        <pre><code>fly secrets list</code></pre>

        <h2>Step 7: Deploy</h2>
        <p>Deploy your application:</p>
        <pre><code>fly deploy</code></pre>
        <p>Fly will build your Docker image and deploy it. This may take a few minutes.</p>

        <h2>Step 8: Verify Deployment</h2>
        <ol>
          <li>Check your app status:</li>
          <pre><code>fly status</code></pre>
          <li>Check API health:</li>
          <pre><code>curl https://your-app-name.fly.dev/health</code></pre>
          <li>View logs if needed:</li>
          <pre><code>fly logs</code></pre>
        </ol>

        <h2>Step 9: Deploy Frontend</h2>
        <p>Deploy the frontend to Vercel:</p>
        <ol>
          <li>Go to <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">Vercel</a></li>
          <li>Import your repository</li>
          <li>Set root directory to <code>web</code></li>
          <li>Add environment variable: <code>VITE_API_URL</code> = <code>https://your-app-name.fly.dev</code></li>
          <li>Deploy</li>
        </ol>

        <h2>Step 10: Setup Cron Jobs (Optional)</h2>
        <p>If you want to run scheduled tasks, set up cron jobs using Fly Machines:</p>
        <pre><code># Set a cron secret
fly secrets set CRON_SECRET="$(openssl rand -hex 32)"

# Create scheduled machines (see api/scripts/setup-fly-cron.sh)
# Sync cron (every 5 minutes)
fly machines create \\
  --name danny-tasks-api-cron-sync \\
  --region iad \\
  --vm-size shared-cpu-1x \\
  --config '{"schedule": {"cron": "*/5 * * * *"}, "restart": {"policy": "no"}}' \\
  --env "CRON_SECRET=your-cron-secret" \\
  --env "API_URL=https://your-app-name.fly.dev" \\
  your-app-name</code></pre>

        <h2>Useful Commands</h2>
        <ul>
          <li><code>fly apps list</code> - List all your apps</li>
          <li><code>fly logs</code> - View application logs</li>
          <li><code>fly ssh console</code> - SSH into your app</li>
          <li><code>fly scale count 2</code> - Scale to 2 instances</li>
          <li><code>fly secrets list</code> - View all secrets</li>
          <li><code>fly postgres list</code> - List Postgres databases</li>
        </ul>

        <h2>Troubleshooting</h2>
        <ul>
          <li><strong>Build fails:</strong> Check that your Dockerfile is correct and in the <code>api/</code> directory</li>
          <li><strong>App won't start:</strong> Check logs with <code>fly logs</code></li>
          <li><strong>Database connection error:</strong> Verify <code>DATABASE_URL</code> secret is set correctly</li>
          <li><strong>Health check fails:</strong> Ensure your app is listening on the correct port (8080)</li>
        </ul>

        <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px' }}>
          <h3>Need Help?</h3>
          <p>
            If you encounter issues, check the <Link to="/docs/deployment/overview">deployment overview</Link> or
            open an issue on <a href="https://github.com/yourusername/tasks" target="_blank" rel="noopener noreferrer">GitHub</a>.
          </p>
        </div>
      </div>
    </Layout>
  );
}
