/**
 * Local Deployment Guide
 * 
 * Detailed guide for running Danny Tasks locally.
 */

import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';

export default function LocalGuide(): JSX.Element {
  return (
    <Layout title="Local Deployment Guide" description="Run Danny Tasks locally">
      <div style={{ padding: '2rem 1rem', maxWidth: '900px', margin: '0 auto' }}>
        <div style={{ marginBottom: '2rem' }}>
          <Link to="/deployment">← Back to Deployment Wizard</Link>
        </div>

        <h1>Local Deployment Guide</h1>
        <p className="text--secondary">
          Run Danny Tasks on your local machine for development or personal use.
        </p>

        <h2>Prerequisites</h2>
        <ul>
          <li>Node.js 22+</li>
          <li>pnpm 8+</li>
          <li>Docker and Docker Compose (for containerized setup)</li>
          <li>PostgreSQL (optional, can use SQLite for development)</li>
          <li>Todoist API key</li>
          <li>Claude API key</li>
        </ul>

        <h2>Option 1: Docker Compose (Recommended)</h2>
        <p>Easiest way to run everything locally with Docker Compose.</p>

        <h3>Step 1: Clone Repository</h3>
        <pre><code>git clone https://github.com/yourusername/tasks.git
cd tasks</code></pre>

        <h3>Step 2: Add Configuration</h3>
        <p>Copy the <code>docker-compose.yml</code> file (generated by the wizard) to your repository root.</p>

        <h3>Step 3: Create Environment File</h3>
        <p>Create a <code>.env</code> file in the repository root:</p>
        <pre><code># Required
TODOIST_API_KEY=your_todoist_api_key
CLAUDE_API_KEY=your_claude_api_key

# Database (for Docker Compose, use the postgres service)
DATABASE_URL=postgresql://tasks:tasks@postgres:5432/tasks

# Optional
NODE_ENV=development
RUN_MODE=http
PORT=8080</code></pre>

        <h3>Step 4: Start Services</h3>
        <pre><code>docker-compose up -d</code></pre>
        <p>This will start:</p>
        <ul>
          <li>API service on <code>http://localhost:8080</code></li>
          <li>PostgreSQL database on <code>localhost:5432</code></li>
          <li>Web frontend on <code>http://localhost:3000</code></li>
        </ul>

        <h3>Step 5: View Logs</h3>
        <pre><code>docker-compose logs -f</code></pre>
        <p>Or view logs for a specific service:</p>
        <pre><code>docker-compose logs -f api</code></pre>

        <h3>Step 6: Stop Services</h3>
        <pre><code>docker-compose down</code></pre>
        <p>To also remove volumes (database data):</p>
        <pre><code>docker-compose down -v</code></pre>

        <h2>Option 2: Development Mode (Without Docker)</h2>
        <p>Run API and web separately for development.</p>

        <h3>Step 1: Install Dependencies</h3>
        <pre><code>pnpm install</code></pre>

        <h3>Step 2: Setup Database</h3>
        <p>Choose one:</p>

        <h4>Option A: SQLite (Easiest for Development)</h4>
        <p>No setup needed! SQLite will be used automatically if <code>DATABASE_URL</code> is not set.</p>

        <h4>Option B: PostgreSQL</h4>
        <ol>
          <li>Install PostgreSQL locally or use Docker:</li>
          <pre><code>docker run -d \\
  --name danny-postgres \\
  -e POSTGRES_DB=tasks \\
  -e POSTGRES_USER=tasks \\
  -e POSTGRES_PASSWORD=tasks \\
  -p 5432:5432 \\
  postgres:15-alpine</code></pre>
          <li>Set <code>DATABASE_URL</code> in your environment</li>
        </ol>

        <h3>Step 3: Configure Environment</h3>
        <p>Create <code>api/.env</code>:</p>
        <pre><code>TODOIST_API_KEY=your_todoist_api_key
CLAUDE_API_KEY=your_claude_api_key
DATABASE_TYPE=postgres
DATABASE_URL=postgresql://tasks:tasks@localhost:5432/tasks
NODE_ENV=development
RUN_MODE=http
PORT=8080</code></pre>

        <h3>Step 4: Run API</h3>
        <pre><code>cd api
pnpm start:http</code></pre>
        <p>API will be available at <code>http://localhost:8080</code></p>

        <h3>Step 5: Run Web (In Another Terminal)</h3>
        <pre><code>cd web
pnpm dev</code></pre>
        <p>Web will be available at <code>http://localhost:5173</code> (Vite default port)</p>

        <h3>Step 6: Run Both Together</h3>
        <p>From the repository root:</p>
        <pre><code>pnpm dev</code></pre>
        <p>This runs both API and web concurrently.</p>

        <h2>Database Migrations</h2>
        <p>The database schema will be created automatically on first run. If you need to run migrations manually:</p>
        <pre><code>cd api
pnpm migrate</code></pre>

        <h2>Development Tips</h2>
        <ul>
          <li>Use SQLite for local development to avoid PostgreSQL setup</li>
          <li>API runs in watch mode with <code>pnpm start:http</code> - changes auto-reload</li>
          <li>Web uses Vite HMR - changes auto-reload in browser</li>
          <li>Check <code>api/.env.example</code> for all available environment variables</li>
        </ul>

        <h2>Troubleshooting</h2>
        <ul>
          <li><strong>Port already in use:</strong> Change <code>PORT</code> in your environment or stop the conflicting service</li>
          <li><strong>Database connection error:</strong> Verify PostgreSQL is running and <code>DATABASE_URL</code> is correct</li>
          <li><strong>API key errors:</strong> Ensure your API keys are set correctly in <code>.env</code></li>
          <li><strong>Build errors:</strong> Run <code>pnpm install</code> to ensure all dependencies are installed</li>
        </ul>

        <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px' }}>
          <h3>Next Steps</h3>
          <p>
            Once running locally, you can:
          </p>
          <ul>
            <li>Test API endpoints at <code>http://localhost:8080</code></li>
            <li>Use the web interface at <code>http://localhost:5173</code></li>
            <li>Run CLI commands: <code>cd api && pnpm cli sync</code></li>
            <li>When ready, deploy to production using our <Link to="/deployment">deployment wizard</Link></li>
          </ul>
        </div>
      </div>
    </Layout>
  );
}
