/**
 * Railway Deployment Guide
 * 
 * Detailed step-by-step guide for deploying to Railway.
 */

import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';

export default function RailwayGuide(): JSX.Element {
  return (
    <Layout title="Railway Deployment Guide" description="Deploy Danny Tasks to Railway">
      <div style={{ padding: '2rem 1rem', maxWidth: '900px', margin: '0 auto' }}>
        <div style={{ marginBottom: '2rem' }}>
          <Link to="/deployment">← Back to Deployment Wizard</Link>
        </div>

        <h1>Railway Deployment Guide</h1>
        <p className="text--secondary">
          Railway is the recommended platform for deploying Danny Tasks. It offers one-click deployment
          with built-in PostgreSQL and a generous free tier.
        </p>

        <h2>Prerequisites</h2>
        <ul>
          <li>GitHub account with your repository</li>
          <li>Railway account (<a href="https://railway.app" target="_blank" rel="noopener noreferrer">Sign up</a>)</li>
          <li>Todoist API key</li>
          <li>Claude API key</li>
        </ul>

        <h2>Step 1: Create Railway Project</h2>
        <ol>
          <li>Go to <a href="https://railway.app" target="_blank" rel="noopener noreferrer">Railway</a> and sign in</li>
          <li>Click "New Project"</li>
          <li>Select "Deploy from GitHub repo"</li>
          <li>Choose your repository</li>
        </ol>

        <h2>Step 2: Add Configuration File</h2>
        <p>
          Add the <code>railway.json</code> file (generated by the wizard) to your repository root.
          Railway will automatically detect and use it.
        </p>

        <h2>Step 3: Add PostgreSQL Database</h2>
        <p>Railway can automatically provision a PostgreSQL database:</p>
        <ol>
          <li>In your Railway project, click "New"</li>
          <li>Select "Database" → "Add PostgreSQL"</li>
          <li>Railway will automatically create the database and set <code>DATABASE_URL</code></li>
        </ol>

        <p>
          <strong>Alternative:</strong> If you're using an external database (Neon, Supabase, etc.),
          skip this step and set <code>DATABASE_URL</code> manually in the next step.
        </p>

        <h2>Step 4: Configure Environment Variables</h2>
        <p>In your Railway service settings, add the following environment variables:</p>
        <ul>
          <li><code>TODOIST_API_KEY</code> - Your Todoist API key</li>
          <li><code>CLAUDE_API_KEY</code> - Your Claude API key</li>
          <li><code>DATABASE_URL</code> - Automatically set if using Railway Postgres, or your external database URL</li>
          <li><code>NODE_ENV</code> - Set to <code>production</code></li>
          <li><code>RUN_MODE</code> - Set to <code>http</code></li>
          <li><code>PORT</code> - Set to <code>8080</code></li>
        </ul>

        <h2>Step 5: Deploy API Service</h2>
        <ol>
          <li>Railway will automatically detect your Dockerfile in the <code>api/</code> directory</li>
          <li>Click "Deploy" to start the deployment</li>
          <li>Wait for the build to complete</li>
          <li>Your API will be available at the generated Railway URL</li>
        </ol>

        <h2>Step 6: Deploy Frontend</h2>
        <p>You can deploy the frontend to Vercel (recommended) or Railway:</p>

        <h3>Option A: Vercel (Recommended)</h3>
        <ol>
          <li>Go to <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">Vercel</a></li>
          <li>Import your repository</li>
          <li>Set root directory to <code>web</code></li>
          <li>Add environment variable: <code>VITE_API_URL</code> = your Railway API URL</li>
          <li>Deploy</li>
        </ol>

        <h3>Option B: Railway</h3>
        <ol>
          <li>Add a new service in Railway</li>
          <li>Select your repository</li>
          <li>Set root directory to <code>web</code></li>
          <li>Add environment variable: <code>VITE_API_URL</code> = your Railway API URL</li>
          <li>Deploy</li>
        </ol>

        <h2>Step 7: Verify Deployment</h2>
        <ol>
          <li>Check API health: <code>https://your-api.railway.app/health</code></li>
          <li>Open your frontend URL</li>
          <li>Enter your API key in the settings</li>
          <li>Start using Danny Tasks!</li>
        </ol>

        <h2>Troubleshooting</h2>
        <ul>
          <li><strong>Build fails:</strong> Check that your Dockerfile is in the <code>api/</code> directory</li>
          <li><strong>Database connection error:</strong> Verify <code>DATABASE_URL</code> is set correctly</li>
          <li><strong>API not responding:</strong> Check Railway logs for errors</li>
        </ul>

        <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px' }}>
          <h3>Need Help?</h3>
          <p>
            If you encounter issues, check the <Link to="/docs/deployment/overview">deployment overview</Link> or
            open an issue on <a href="https://github.com/yourusername/tasks" target="_blank" rel="noopener noreferrer">GitHub</a>.
          </p>
        </div>
      </div>
    </Layout>
  );
}
