/**
 * Render Deployment Guide
 * 
 * Detailed step-by-step guide for deploying to Render.
 */

import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';

export default function RenderGuide(): JSX.Element {
  return (
    <Layout title="Render Deployment Guide" description="Deploy Danny Tasks to Render">
      <div style={{ padding: '2rem 1rem', maxWidth: '900px', margin: '0 auto' }}>
        <div style={{ marginBottom: '2rem' }}>
          <Link to="/deployment">← Back to Deployment Wizard</Link>
        </div>

        <h1>Render Deployment Guide</h1>
        <p className="text--secondary">
          Render offers a free tier with managed PostgreSQL, making it a great option for getting started.
        </p>

        <h2>Prerequisites</h2>
        <ul>
          <li>GitHub account with your repository</li>
          <li>Render account (<a href="https://render.com" target="_blank" rel="noopener noreferrer">Sign up</a>)</li>
          <li>Todoist API key</li>
          <li>Claude API key</li>
        </ul>

        <h2>Step 1: Create Blueprint</h2>
        <ol>
          <li>Go to <a href="https://render.com" target="_blank" rel="noopener noreferrer">Render Dashboard</a></li>
          <li>Click "New +" → "Blueprint"</li>
          <li>Connect your GitHub repository</li>
          <li>Render will detect the <code>render.yaml</code> file</li>
        </ol>

        <h2>Step 2: Add Configuration File</h2>
        <p>
          Add the <code>render.yaml</code> file (generated by the wizard) to your repository root.
          This file defines your services (API and optionally Postgres).
        </p>

        <h2>Step 3: Review Services</h2>
        <p>Render will create the following services based on your <code>render.yaml</code>:</p>
        <ul>
          <li><strong>danny-api</strong> - Your API service (Docker)</li>
          <li><strong>danny-db</strong> - PostgreSQL database (if using managed Postgres)</li>
        </ul>

        <h2>Step 4: Configure Environment Variables</h2>
        <p>For the <code>danny-api</code> service, add these environment variables:</p>
        <ul>
          <li><code>TODOIST_API_KEY</code> - Your Todoist API key</li>
          <li><code>CLAUDE_API_KEY</code> - Your Claude API key</li>
          <li><code>DATABASE_URL</code> - Automatically set if using Render Postgres, or your external database URL</li>
          <li><code>NODE_ENV</code> - Set to <code>production</code></li>
          <li><code>RUN_MODE</code> - Set to <code>http</code></li>
          <li><code>PORT</code> - Set to <code>8080</code></li>
        </ul>

        <h2>Step 5: Deploy</h2>
        <ol>
          <li>Click "Apply" to create all services</li>
          <li>Render will build and deploy your API</li>
          <li>Wait for the deployment to complete (first deploy may take a few minutes)</li>
          <li>Your API will be available at the generated Render URL</li>
        </ol>

        <h2>Step 6: Deploy Frontend</h2>
        <p>You can deploy the frontend to Vercel (recommended) or Render:</p>

        <h3>Option A: Vercel (Recommended)</h3>
        <ol>
          <li>Go to <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">Vercel</a></li>
          <li>Import your repository</li>
          <li>Set root directory to <code>web</code></li>
          <li>Add environment variable: <code>VITE_API_URL</code> = your Render API URL</li>
          <li>Deploy</li>
        </ol>

        <h3>Option B: Render Static Site</h3>
        <ol>
          <li>In Render, click "New +" → "Static Site"</li>
          <li>Connect your repository</li>
          <li>Set build command: <code>cd web && pnpm install && pnpm build</code></li>
          <li>Set publish directory: <code>web/dist</code></li>
          <li>Add environment variable: <code>VITE_API_URL</code> = your Render API URL</li>
          <li>Deploy</li>
        </ol>

        <h2>Step 7: Verify Deployment</h2>
        <ol>
          <li>Check API health: <code>https://your-api.onrender.com/health</code></li>
          <li>Open your frontend URL</li>
          <li>Enter your API key in the settings</li>
          <li>Start using Danny Tasks!</li>
        </ol>

        <h2>Free Tier Limitations</h2>
        <ul>
          <li>Services spin down after 15 minutes of inactivity</li>
          <li>First request after spin-down may be slow (cold start)</li>
          <li>Consider upgrading for production use</li>
        </ul>

        <h2>Troubleshooting</h2>
        <ul>
          <li><strong>Build fails:</strong> Check that your Dockerfile is in the <code>api/</code> directory</li>
          <li><strong>Database connection error:</strong> Verify <code>DATABASE_URL</code> is set correctly</li>
          <li><strong>Service won't start:</strong> Check Render logs for errors</li>
          <li><strong>Cold starts:</strong> Normal on free tier, consider upgrading</li>
        </ul>

        <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'var(--ifm-color-emphasis-100)', borderRadius: '8px' }}>
          <h3>Need Help?</h3>
          <p>
            If you encounter issues, check the <Link to="/docs/deployment/overview">deployment overview</Link> or
            open an issue on <a href="https://github.com/yourusername/tasks" target="_blank" rel="noopener noreferrer">GitHub</a>.
          </p>
        </div>
      </div>
    </Layout>
  );
}
